# Generated by Django 3.1.7 on 2022-03-19 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokerusers', '0002_auto_20220318_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminpoker',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clientpoker',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
