# Generated by Django 3.1.7 on 2022-04-08 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokerusers', '0004_auto_20220327_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cellphone',
            field=models.CharField(default='987654321', max_length=12),
        ),
    ]
