# Generated by Django 3.1.7 on 2022-03-18 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComparativeHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameComparative', models.CharField(default='DF_Comparative', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DoubleComparation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameComparation', models.CharField(default='Comparation', max_length=200)),
                ('colors', models.CharField(default='DEFAULT', max_length=1010)),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moveName', models.CharField(default='DF_Move', max_length=200)),
                ('colors', models.CharField(default='DEFAULT', max_length=1010)),
            ],
        ),
        migrations.CreateModel(
            name='TripleComparation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameComparation', models.CharField(default='Comparation', max_length=200)),
                ('colors', models.CharField(default='DEFAULT', max_length=1010)),
                ('doubleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triplecomparation', to='principal.doublecomparation')),
            ],
        ),
        migrations.AddField(
            model_name='doublecomparation',
            name='moveId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doublecomparation', to='principal.move'),
        ),
        migrations.CreateModel(
            name='ComparativeADD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HeaderID', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='principal.comparativeheader')),
                ('moveId', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='principal.move')),
            ],
        ),
    ]
