# Generated by Django 3.1.7 on 2022-04-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doublecomparation',
            name='observation',
            field=models.CharField(default='DEFAULT', max_length=500),
        ),
        migrations.AddField(
            model_name='doublecomparation',
            name='tags',
            field=models.CharField(default='DEFAULT', max_length=200),
        ),
        migrations.AddField(
            model_name='move',
            name='observation',
            field=models.CharField(default='DEFAULT', max_length=500),
        ),
        migrations.AddField(
            model_name='move',
            name='tags',
            field=models.CharField(default='DEFAULT', max_length=200),
        ),
        migrations.AddField(
            model_name='triplecomparation',
            name='observation',
            field=models.CharField(default='DEFAULT', max_length=500),
        ),
        migrations.AddField(
            model_name='triplecomparation',
            name='tags',
            field=models.CharField(default='DEFAULT', max_length=200),
        ),
        migrations.DeleteModel(
            name='ComparativeADD',
        ),
        migrations.DeleteModel(
            name='ComparativeHeader',
        ),
    ]
