# Generated by Django 3.1.7 on 2022-03-18 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileName', models.CharField(default='DEFAULT', max_length=200)),
                ('description', models.CharField(default='DEFAULT', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TripleVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colors', models.CharField(default='DEFAULT', max_length=500)),
                ('description', models.CharField(default='DEFAULT', max_length=200)),
                ('versionname', models.CharField(default='DEFAULT', max_length=500)),
                ('moveId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tripleversion', to='principal.triplecomparation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TripleAssignation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfilId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profilemoves.profile')),
                ('versionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tripleassignation', to='profilemoves.tripleversion')),
            ],
        ),
        migrations.CreateModel(
            name='SingleVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colors', models.CharField(default='DEFAULT', max_length=500)),
                ('description', models.CharField(default='DEFAULT', max_length=200)),
                ('versionname', models.CharField(default='DEFAULT', max_length=500)),
                ('moveId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='singleversion', to='principal.move')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SingleAssignation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfilId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profilemoves.profile')),
                ('versionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='singleassignation', to='profilemoves.singleversion')),
            ],
        ),
        migrations.CreateModel(
            name='DoubleVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colors', models.CharField(default='DEFAULT', max_length=500)),
                ('description', models.CharField(default='DEFAULT', max_length=200)),
                ('versionname', models.CharField(default='DEFAULT', max_length=500)),
                ('moveId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doubleversion', to='principal.doublecomparation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DoubleAssignation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfilId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profilemoves.profile')),
                ('versionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doubleassignation', to='profilemoves.doubleversion')),
            ],
        ),
        migrations.AddConstraint(
            model_name='tripleassignation',
            constraint=models.UniqueConstraint(fields=('perfilId', 'versionId'), name='triple_asignacion '),
        ),
        migrations.AddConstraint(
            model_name='singleassignation',
            constraint=models.UniqueConstraint(fields=('perfilId', 'versionId'), name='singular_asignacion '),
        ),
        migrations.AddConstraint(
            model_name='doubleassignation',
            constraint=models.UniqueConstraint(fields=('perfilId', 'versionId'), name='doble_asignacion '),
        ),
    ]
