# Generated by Django 3.1.7 on 2022-03-21 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokerusers', '0003_auto_20220318_2134'),
        ('profilemoves', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientprofile', to='pokerusers.clientpoker')),
                ('profileId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientprofile', to='profilemoves.profile')),
            ],
        ),
    ]
