# Generated by Django 3.1.7 on 2022-04-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilemoves', '0002_clientprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doubleversion',
            name='description',
            field=models.TextField(default='DEFAULT', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(default='DEFAULT', max_length=200),
        ),
        migrations.AlterField(
            model_name='singleversion',
            name='description',
            field=models.TextField(default='DEFAULT', max_length=200),
        ),
        migrations.AlterField(
            model_name='tripleversion',
            name='description',
            field=models.TextField(default='DEFAULT', max_length=200),
        ),
    ]
